-- Built-in categories (owner_id is null). Users can add their own and archive any they don't use.
INSERT INTO "categories" ("owner_id", "kind", "name") VALUES
  (NULL, 'expense', 'Groceries'),
  (NULL, 'expense', 'Food & dining'),
  (NULL, 'expense', 'Rent'),
  (NULL, 'expense', 'Utilities'),
  (NULL, 'expense', 'Mobile & internet'),
  (NULL, 'expense', 'Transport'),
  (NULL, 'expense', 'Fuel'),
  (NULL, 'expense', 'Shopping'),
  (NULL, 'expense', 'Health & medical'),
  (NULL, 'expense', 'Education'),
  (NULL, 'expense', 'Entertainment'),
  (NULL, 'expense', 'Travel'),
  (NULL, 'expense', 'Personal care'),
  (NULL, 'expense', 'Household'),
  (NULL, 'expense', 'Insurance'),
  (NULL, 'expense', 'Gifts & donations'),
  (NULL, 'expense', 'Taxes'),
  (NULL, 'expense', 'Fees & charges'),
  (NULL, 'expense', 'Kids'),
  (NULL, 'expense', 'Other expense'),
  (NULL, 'income', 'Salary'),
  (NULL, 'income', 'Business'),
  (NULL, 'income', 'Freelance'),
  (NULL, 'income', 'Interest'),
  (NULL, 'income', 'Dividends'),
  (NULL, 'income', 'Rent received'),
  (NULL, 'income', 'Bonus'),
  (NULL, 'income', 'Cashback & rewards'),
  (NULL, 'income', 'Gifts received'),
  (NULL, 'income', 'Other income')
ON CONFLICT DO NOTHING;
